### ISSUE TITLE
"plugin.video.abelhas" Add to Library (TVShow) - Batch / Blank Space

### ISSUE THREAD

**Issue by jorgeavlobo** [Mafarricos/Mafarricos-xbmc-dev-addons#3]
In Abelhas, Add to Library (TVShow) - Batch, it won't work if the series is called:
Castle s01e01
Castle s01e02
Castle S01e03
etc, etc...

I guess it is because of the space.
Can the plugin accomodate this detail in TV Series naming?
Thanks

**Comment by Mafarricos** [comment]
Should be fixed in 1.0.2i version.

**Comment by jorgeavlobo** [comment]
Not fixed I believe...
Example:
Castle S01E01.mkv
Castle S01E02.mkv
Castle S01E03.mkv

Another thing I've noticed:
If name = Castle.2009.s06e01.mkv
It will create folder "Castle 2009" and not "Castle", it will create problems if the different seasons are named differently.

Thanks!

**Comment by Mafarricos** [comment]
I what abelhas is that I tested with some named Castle S01E01, etc and worked.

**Comment by Mafarricos** [comment]
Should be fixed in 1.0.3~beta001

About Castle 2009 or Castle. It will create 2 folders but in library will be in same folder. Only physical folders will be different.

But it will work.

Don't forget that you can have different ways to name a folder. So is difficult to control all.
Open a different issue with 2009 or not having 2009 and I will see how can be controlled on the future.
But will be difficult.
Imagine the TvShow "Space 1999" if I remove years from the name of tv show it will be named Space only that is incorrect.
